export class Timeline{
    
timelinedata=[
    {
        'poster_user':"Balasivaguru",
        'poster_date':"23/1/19",
        'poster_link':"../../assets/li_1.png",
        'poster_like':"like"
    },
    {
        'poster_user':"Balasivaguru",
        'poster_date':"23/1/19",
        'poster_link':"../../assets/li_2.png",
        'poster_like':"like_active"
    },
    {
        'poster_user':"Balasivaguru",
        'poster_date':"23/1/19",
        'poster_link':"../../assets/li_3.png",
        'poster_like':"like"
    },
    {
        'poster_user':"Balasivaguru",
        'poster_date':"23/1/19",
        'poster_link':"../../assets/li_4.png",
        'poster_like':"like_active"
    },
]
arra=[1,3,5]
}